"""Agregar fecha_modificacion para tracking de cambios

Revision ID: 9184783d9075
Revises: 
Create Date: 2025-11-26 21:00:40.763508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9184783d9075'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensayos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_modificacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensayos', schema=None) as batch_op:
        batch_op.drop_column('fecha_modificacion')

    # ### end Alembic commands ###
